ShopTARge23/ShopTARge23/Models/Kindergarten/KindergartenCreateUpdateViewModel.cs
using ShopTARge23.Models.Spaceships;

namespace ShopTARge23.Models.Kindergarten
{
    public class KindergartenCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher { get; set; }
        public List<IFormFile> Files { get; set; }
        public List<KindergartenImageViewModel> Image {  get; set; }
            = new List<KindergartenImageViewModel>();
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Kindergarten/KindergartenDeleteViewModel.cs
using ShopTARge23.Models.Spaceships;

namespace ShopTARge23.Models.Kindergarten
{
    public class KindergartenDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher {  get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Kindergarten/KindergartenDetailsViewModel.cs
using ShopTARge23.Models.Spaceships;

namespace ShopTARge23.Models.Kindergarten
{
    public class KindergartenDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher {  get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Kindergarten/KindergartenImageViewModel.cs
using ShopTARge23.Models.Kindergarten;
using Microsoft.AspNetCore.Mvc;

namespace ShopTARge23.Models.Kindergarten
{
    public class KindergartenImageViewModel
    {
        public Guid ImageId { get; set; }
        public string ImageTitle { get; set; }
        public byte[] ImageData { get; set; }
        public string Image {  get; set; }
        public Guid? KindergartenId { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Kindergarten/KindergartenIndexViewModel.cs
namespace ShopTARge23.Models.Kindergarten
{
    public class KindergartenIndexViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Spaceships/ImageViewModel.cs
namespace ShopTARge23.Models.Spaceships
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? FilePath { get; set; }
        public Guid? SpaceshipId { get; set; }
    }
}

ShopTARge23/ShopTARge23/Controllers/KindergartenController.cs
using Microsoft.AspNetCore.Mvc;
using ShopTARge23.Data;
using ShopTARge23.Models.Kindergarten;
using ShopTARge23.Core.ServiceInterface;
using ShopTARge23.Core.Dto;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ShopTARge23.Controllers
{
    public class KindergartenController : Controller
    {
        private readonly ShopTARge23Context _context;
        private readonly IKindergartenServices _kindergartenServices;
        private readonly IFileServices _fileServices;
        public KindergartenController
            (
            ShopTARge23Context context,
            IKindergartenServices kindergartenServices,
            IFileServices fileServices
            )
        {
            _context = context;
            _kindergartenServices = kindergartenServices;
            _fileServices = fileServices;
        }

        public IActionResult Index()
        {
            var result = _context.Kindergartens
                .Select(x => new KindergartenIndexViewModel
                {
                    Id = x.Id,
                    GroupName = x.GroupName,
                    KindergartenName = x.KindergartenName,
                    Teacher = x.Teacher
                });
            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var result = new KindergartenCreateUpdateViewModel();

            return View("CreateUpdate", result);
        }

        [HttpPost]
        public async Task<IActionResult> Create(KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                Teacher = vm.Teacher,
                CreatedAt = DateTime.Now,
                UpdatedAt = DateTime.Now,
                Files = vm.Files,
                Image = vm.Image.
                    Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        KindergartenId = x.KindergartenId,
                    }).ToArray()
                
            };

            var result = await _kindergartenServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailsAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }

            var images = await _context.FileToDatabases
                .Where(x => x.KindergartenId == id)
                .Select(y => new KindergartenImageViewModel
                {
                    KindergartenId = y.KindergartenId,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = $"data:image/gif;base64,{Convert.ToBase64String(y.ImageData)}"
                }).ToArrayAsync();

            var vm = new KindergartenDetailsViewModel
            {
                Id = kindergarten.Id,
                GroupName = kindergarten.GroupName,
                ChildrenCount = kindergarten.ChildrenCount,
                KindergartenName = kindergarten.KindergartenName,
                Teacher = kindergarten.Teacher,
                CreatedAt = kindergarten.CreatedAt,
                UpdatedAt = kindergarten.UpdatedAt
            };
            vm.Image.AddRange(images);


            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailsAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }

            var images = await _context.FileToDatabases
                .Where(x => x.KindergartenId == id)
                .Select(y => new KindergartenImageViewModel
                {
                    KindergartenId = y.KindergartenId,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = $"data:image/gif;base64,{Convert.ToBase64String(y.ImageData)}"
                }).ToArrayAsync();

            var vm = new KindergartenCreateUpdateViewModel
            {
                Id = kindergarten.Id,
                GroupName = kindergarten.GroupName,
                ChildrenCount = kindergarten.ChildrenCount,
                KindergartenName = kindergarten.KindergartenName,
                Teacher = kindergarten.Teacher,
                CreatedAt = kindergarten.CreatedAt,
                UpdatedAt = kindergarten.UpdatedAt
            };
            vm.Image.AddRange(images);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = DateTime.Now,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        KindergartenId = x.KindergartenId
                    }).ToArray()
            };

            var result = await _kindergartenServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailsAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }

            var images = await _context.FileToDatabases
                .Where(x => x.KindergartenId == id)
                .Select(y => new KindergartenImageViewModel
                {
                    KindergartenId = y.KindergartenId,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = $"data:image/gif;base64,{Convert.ToBase64String(y.ImageData)}"
                }).ToArrayAsync();

            var vm = new KindergartenDeleteViewModel
            {
                Id = kindergarten.Id,
                GroupName = kindergarten.GroupName,
                ChildrenCount = kindergarten.ChildrenCount,
                KindergartenName = kindergarten.KindergartenName,
                Teacher = kindergarten.Teacher,
                CreatedAt = kindergarten.CreatedAt,
                UpdatedAt = kindergarten.UpdatedAt
            };
            vm.Image.AddRange(images);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var kindergartenId = await _kindergartenServices.Delete(id);

            if(kindergartenId == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImage(KindergartenImageViewModel vm)
        {
            var dto = new FileToDatabaseDto
            {
                Id = vm.ImageId
            };

            var image = await _fileServices.RemoveImageFromDatabase(dto);

            if(image != null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARge23/ShopTARge23/Views/Kindergarten/CreateUpdate.cshtml
@model ShopTARge23.Models.Kindergarten.KindergartenCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="UpdatedAt" type="hidden" />
        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="GroupName" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="ChildrenCount" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="KindergartenName" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Teacher" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control custom-file-input" asp-for="Files" multiple type="file" />
                    <label class="custom-file-label">Choose file...</label>
                </div>
            </div>
        </div>

        <div>
            @foreach (var images in Model.Image)
            {
                <partial name="_Images" model="images" />
                <input asp-action="RemoveImage" asp-controller="Kindergarten" asp-route-imageId="@images.ImageId" type="submit"
                       class="btn btn-danger" value="Remove Image" />
            }
        </div>

        <hr />

        @if (Model.Id.HasValue)
        {
            <input asp-action="Update" asp-controller="Kindergarten" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="Create" asp-controller="Kindergarten" type="submit" class="btn btn-primary" value="Create" />
        }

        <a asp-action="Index" asp-controller="Kindergartens class="btn btn-success">Back</a>
    </form>
</div>

ShopTARge23/ShopTARge23/Views/Kindergarten/Delete.cshtml
@model ShopTARge23.Models.Kindergarten.KindergartenDeleteViewModel


<h1>Delete</h1>

<div>
    <h4>Kindergarten Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.KindergartenName)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.KindergartenName)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.GroupName)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.GroupName)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.ChildrenCount)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.ChildrenCount)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Teacher)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Teacher)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.CreatedAt)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.CreatedAt)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.UpdatedAt)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.UpdatedAt)</dd>
    </dl>

    <div>
        @foreach (var image in Model.Image)
        {
            <div class="image-container">
                <img src="@image.Image" alt="@image.ImageTitle" class="img-thumbnail" style="max-width: 200px;" />
                <p>@image.ImageTitle</p>
            </div>
        }
    </div>

    <hr />
    <form asp-action="DeleteConfirmation" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="Kindergarten" class="btn btn-success">Back</a>
    </form>
</div>

ShopTARge23/ShopTARge23/Views/Kindergarten/Details.cshtml
@model ShopTARge23.Models.Kindergarten.KindergartenDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Kindergarten Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.KindergartenName)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.KindergartenName)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.GroupName)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.GroupName)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.ChildrenCount)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.ChildrenCount)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Teacher)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Teacher)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.CreatedAt)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.CreatedAt)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.UpdatedAt)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.UpdatedAt)</dd>
    </dl>

    <div>
        @foreach (var image in Model.Image)
        {
            <div class="image-container">
                <img src="@image.Image" alt="@image.ImageTitle" class="img-thumbnail" style="max-width: 200px;" />
                <p>@image.ImageTitle</p>
            </div>
        }
    </div>

    <a asp-action="Index" asp-controller="Kindergarten" class="btn btn-danger">Back</a>
</div>

ShopTARge23/ShopTARge23/Views/Kindergarten/Index.cshtml
@model IEnumerable<ShopTARge23.Models.Kindergarten.KindergartenIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="Kindergarten" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    Kindergartens
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Group Name</th>
                <th scope="col">Children Count</th>
                <th scope="col">Kindergarten Name</th>
                <th scope="col">Teacher</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var kindergartens in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@kindergartens.GroupName</td>
                    <td>@kindergartens.ChildrenCount</td>
                    <td>@kindergartens.KindergartenName</td>
                    <td>@kindergartens.Teacher</td>
                    <td>
                        <a asp-action="details" asp-controller="Kindergarten" asp-route-id="@kindergartens.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="Kindergarten" asp-route-id="@kindergartens.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="Kindergarten" asp-route-id="@kindergartens.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber += 1;
            }
        </tbody>
    </table>
</form>

ShopTARge23/ShopTARge23/Views/Kindergarten/_Images.cshtml
@model ShopTARge23.Models.Kindergarten.KindergartenImageViewModel


<div class="form-group row col-sm-4 offset-2">
    <div>@Model.ImageTitle</div>
    <img class="card-image-top" src="@Model.Image" asp-append-version="true" />
</div>